[tool.poetry]
name = "learning-tdd"
version = "0.1.0"
description = ""
authors = ["Pablo Martínez Pérez <pablompg@pm.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^7.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
